// Generated by gencpp from file racecar_package/customize_msg.msg
// DO NOT EDIT!


#ifndef RACECAR_PACKAGE_MESSAGE_CUSTOMIZE_MSG_H
#define RACECAR_PACKAGE_MESSAGE_CUSTOMIZE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace racecar_package
{
template <class ContainerAllocator>
struct customize_msg_
{
  typedef customize_msg_<ContainerAllocator> Type;

  customize_msg_()
    : name()
    , age(0)
    , height(0.0)  {
    }
  customize_msg_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int32_t _age_type;
  _age_type age;

   typedef float _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::racecar_package::customize_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::racecar_package::customize_msg_<ContainerAllocator> const> ConstPtr;

}; // struct customize_msg_

typedef ::racecar_package::customize_msg_<std::allocator<void> > customize_msg;

typedef boost::shared_ptr< ::racecar_package::customize_msg > customize_msgPtr;
typedef boost::shared_ptr< ::racecar_package::customize_msg const> customize_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::racecar_package::customize_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::racecar_package::customize_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace racecar_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'racecar_package': ['/home/rmshe/project_ws/src/racecar_package/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::racecar_package::customize_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::racecar_package::customize_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_package::customize_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::racecar_package::customize_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_package::customize_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::racecar_package::customize_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::racecar_package::customize_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0478132ca0c3bd1c734b5491000dabb1";
  }

  static const char* value(const ::racecar_package::customize_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0478132ca0c3bd1cULL;
  static const uint64_t static_value2 = 0x734b5491000dabb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::racecar_package::customize_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "racecar_package/customize_msg";
  }

  static const char* value(const ::racecar_package::customize_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::racecar_package::customize_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
int32 age\n\
float32 height\n\
";
  }

  static const char* value(const ::racecar_package::customize_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::racecar_package::customize_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct customize_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::racecar_package::customize_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::racecar_package::customize_msg_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RACECAR_PACKAGE_MESSAGE_CUSTOMIZE_MSG_H
